dist: trusty
sudo: required
language: node_js
node_js:
  - '6.9.1'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g angular-cli
  - npm install

script:
  # For dev branch
  - if [[ "$TRAVIS_BRANCH" == "dev" ]]; then npm run build:dev; fi

  # For master branch
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then npm run build:prod; fi

  - npm run test:no-watch

after_success:
  # For dev branch
  - echo $DOCKER_USER
  - echo $DOCKER_PASS
  - |
      if [ "$TRAVIS_BRANCH" == "dev" ]; then
        docker build -t compiax/odin-web:dev-latest .
        docker tag compiax/odin-web:dev-latest compiax/odin-web:dev-latest
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker push compiax/odin-web:dev-latest
      fi

  # For master branch
  - |
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker build -t compiax/odin-web:latest .
        docker tag compiax/odin-web:latest compiax/odin-web:latest
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker push compiax/odin-web:latest
      fi
